### ISSUE TITLE
TODO - login

### ISSUE THREAD

**Issue by Pandademic** [Pandademic/mac2#1]
- [x] add background
- [ ] add working button  
- [x] #5
- [ ] make lock better
- [ ] #4
- [ ] #3
- [x] optimize background image
- [x] fact check css
- [x] maybe: change background image
